sudo: required
language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

services:
  - docker

script:
  - rm -rf www/
  - npm run ionic:build --prod --aot --minifyJs --minifyCss --optimizeJs
  - npm install md5-file
  - node file-revision.js
  - docker build -t pacworx/atp-web .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push pacworx/atp-web

notifications:
  slack: pacworx:M2sZGPNSvxzvLD4XkaUF4oGI
