sudo: required
language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

script:
  - rm -rf www/
  - npm run ionic:build --prod --aot --minifyJs --minifyCss --optimizeJs
  - npm install md5-file
  - node file-revision.js

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.askthepeople.io
  skip_cleanup: true
  local_dir: www
  region: "ap-southeast-2"

notifications:
  slack: pacworx:M2sZGPNSvxzvLD4XkaUF4oGI
